### ISSUE TITLE
Could this tool be migerated to Android arm devices?

### ISSUE THREAD

**Issue by dpinthinker** [aayasin/perf-tools#5]
Hi, I am a compliler guy on Android devices. By reading the _A Top-Down Method for Performance Analysis and Counters Architecture_, I found it is very useful to analysis the program’s performance. 

But it seems that there is not a similar tool to do the same thing on Android ARM based devices.

Is is possible to migerated this tool to Android devices? AOSP has provided a tool simpleperf to read PMU infos.

**Comment by aayasin** [comment]
Hello and thanks for the interest.

This toolset relies on the TMA method as implemented by `pmu-tools/toplev` That is imported here. Toplev supports variety of Intel server and client cores including Atom. @andikleen Would better relate wrt ARM support, if any. 

With that said, note TMA relies on designated performance counters that need to be available in the underlying processor. The [dereferenced paper](bit.ly/tma-ispass14) calls for 8 simple perf counters over a commodity PMU design, to feature the tree’s key nodes. I believe @algrant-arm can help on perf analysis tools for ARM, and hopefully can shed some light on TMA support. 

Yet, some parts of this package should work on ARM. For example steps 0-3 of the profile command log setup, run default `perf stat and record`. The setup of the system for proper performance analysis may be helpful too.

-Ahmad

**Comment by dpinthinker** [comment]
Thank you very much for detailed reply, Ahmad @aayasin .
The url of "dereferenced paper" seems broken, could you help give a new one?

**Comment by dpinthinker** [comment]
did you mean this one?
https://drive.google.com/file/d/0B_SDNxjh2Wbcc0lWemFNSGMzLTA/view

**Comment by aayasin** [comment]
Yes. It is my original paper you mentioned in the initial message of this query. Typing bit.ly/tma-ispass14 in your browser should redirect to it. I fixed the URL in my previous reply too.

**Comment by dpinthinker** [comment]
Fine，Thank you!

**Comment by dpinthinker** [comment]
@andikleen Andi, Could you give some info about TMA ARM supporting?

**Comment by andikleen** [comment]
If someone submitted an ARM model for toplev I would consider it, but I don't have any plans to work on it myself.

**Comment by dpinthinker** [comment]
> If someone submitted an ARM model for toplev I would consider it, but I don't have any plans to work on it myself.

Thank you, Andi. It seems there is no one doing it currently.

**Comment by algrant-arm** [comment]
Thanks for bringing this up. Top-down is something we care about. I think there are several questions here - firstly how well does top-down work for different types of microarchitecture (e.g. ones without a unified scheduler), secondly does Arm have the right events for top-down, and thirdly, if we did have top-down for Arm, should we try and integrate that into pmu-tools, or would it be cleaner to have a separate tool - given that, for example, if the tool needs to go off and fetch event descriptions, that would likely be from an Arm site rather than download.01.org.

It would be interesting to hear if top-down in general, or pmu-tools in particular, have worked on other vendor microarchitectures - AMD for example.
